apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: yas-java
  namespace: observability
spec:
  exporter:
    endpoint: http://yas-otel-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.namespace=yas-msa
